print('My name is Sherif Shawky Abdelmenem')
print('My age is 22 years old')
print('My department is ECE')
print('MY graduation year is 2024 isa')
print('My favourite team is Computer Vision')
print('just a line to make a request on')
